@startuml
'https://plantuml.com/class-diagram

class CPU {
+ initialize()
}

class HD {
+ initialize()
}

class RAM {
+ initialize()
+ loadOS()
+ loadOSKernelImage()
+ loadDrivers()
+ startServices()
}

class Display {
+ initialize()
}

class BIOS {
+ initialize()
}

class ROM {
+ getOSKernelImage()
}

@enduml