package dev.kaldiroglu.dp.structural.facade.gof;

/** Subsystem: abstract code generator — walks AST and emits bytecode. */
public abstract class CodeGenerator {
    protected final BytecodeStream output = new BytecodeStream();

    public abstract void visit(ProgramNode node);

    /** Client or Facade calls this to collect generated bytecode. */
    public String getBytecode() { return output.getBytecode(); }
}
