@startuml
skinparam dpi 300
!theme blueprint

class Citizen{
   + void askForJob()
   + void tellProblem()
}

class ProxyPM {
  + void listen(String problem)
  + void findJob(String name)
  - boolean sortOut(String problem)
  - void delegate(String problem)
}

class RealPM {
  + void listen(String problem)
  + void findJob(String name)
  - void resolve(String problem)
}

Citizen -> ProxyPM
ProxyPM -> RealPM
@enduml
